server:
  port: 8080
spring:
  application:
    name: ramenlog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://54.85.23.80:3306/ramenlog?serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 5144
  mail:
    host: smtp.gmail.com
    port: 587
    username: shimakaazee@gmail.com
    password: leulbggacmzeviez
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:

    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
ramenlog:
  path: /opt/project/img/